In [10]:
from ReplayBuffer import CNNReplayBuffer
import numpy as np
buffer = CNNReplayBuffer(1000, 3)

for i in range(10):
    state = np.random.rand(2,2,2)
    action = np.random.randint(1, 11)
    reward = np.random.randint(1, 11)
    next_state = np.random.rand(2,2,2)
    done = np.random.randint(0, 3)
    if done == 0:
        done = False
    else:
        done = True
    buffer.push(state, action, reward, next_state, done)
state = np.random.rand(2,2,2)
print(buffer.get_q_input(state).shape)

(6, 2, 2)
(6, 2, 2)
(6, 2, 2)
(6, 2, 2)
(6, 2, 2)
(6, 2, 2)
(6, 2, 2)
(6, 2, 2)


In [13]:
sample = buffer.pop(2)
print(sample[0].state, sample[1].state)

[[[0.771953   0.10816357]
  [0.22419262 0.59198888]]

 [[0.76528243 0.09581458]
  [0.87635932 0.0404973 ]]

 [[0.25509668 0.90899924]
  [0.96074099 0.57964782]]

 [[0.97142116 0.26682351]
  [0.65161911 0.05477979]]

 [[0.771953   0.10816357]
  [0.22419262 0.59198888]]

 [[0.76528243 0.09581458]
  [0.87635932 0.0404973 ]]]
